name: covid
channels:
  - defaults
dependencies:
  - python=3.7.7
  - coverage=5.0
  - flake8=3.7.9
  - psycopg2=2.8.4
  - requests=2.24.0
  - plotly=4.6.0
  - pip=20.0.2
  - pip:
      - radon==4.1.0
      - bs4==0.0.1
      - django==3.0.3
