# Generated by Django 3.0.3 on 2020-07-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Datum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('cases', models.IntegerField(default=0, verbose_name='Cases')),
                ('deaths', models.IntegerField(default=0, verbose_name='Deaths')),
                ('recoveries', models.IntegerField(default=0, verbose_name='Recoveries')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plots.Country')),
            ],
        ),
    ]
