# Generated by Django 3.0.3 on 2020-07-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datum',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
