# Generated by Django 3.0.3 on 2020-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_auto_20200729_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='tag',
            field=models.CharField(default='spain', max_length=50, verbose_name='Tag'),
            preserve_default=False,
        ),
    ]
