# Generated by Django 3.0.3 on 2020-07-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_country_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='line_color',
            field=models.CharField(default='#000000', max_length=8, verbose_name='Color'),
        ),
    ]
