# Generated by Django 3.0.3 on 2020-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0005_country_line_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso',
            field=models.CharField(default='xxx', max_length=6, verbose_name='ISO code'),
        ),
    ]
